export const REQUEST_TYPE = "_REQUEST";
export const SUCCESS_TYPE = "_SUCCESS";
export const FAILURE_TYPE = "_FAILURE";
export const SET_LEADER_TYPE = "SET_LEADER_TYPE";
export const LOGIN_TYPE = "LOGIN";
export const LOGOUT_TYPE = "LOGOUT_TYPE";
export const GET_USER_TYPE = "GET_USER_TYPE";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const SIGNUP = 'SIGNUP';

// LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_REQ = "GET_USER_REQ";
export const GET_USER_FAILED = "GET_USER_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

//USER PROFILE
export const USER_PROFILE_REQ = "USER_PROFILE_REQ";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILED = "USER_PROFILE_FAILED";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const VERIFY_CODE = "VERIFY_CODE";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";

// VIDEO
export const GET_VIDEO_ALL_REQ = "GET_VIDEO_ALL_REQ";
export const GET_VIDEO_ALL_SUCCESS = "GET_VIDEO_ALL_SUCCESS";
export const GET_VIDEO_ALL_FAILED = "GET_VIDEO_ALL_FAILED";
export const GET_VIDEO_DETAIL_REQ = "GET_VIDEO_DETAIL_REQ";
export const GET_VIDEO_DETAIL_SUCCESS = "GET_VIDEO_DETAIL_SUCCESS";
export const GET_VIDEO_DETAIL_FAILED = "GET_VIDEO_DETAIL_FAILED";

// FITUR UT CONNECT
export const GET_FITUR_UTCONNECT_REQ = "GET_FITUR_UTCONNECT_REQ";
export const GET_FITUR_UTCONNECT_FAILED = "GET_FITUR_UTCONNECT_FAILED";
export const GET_FITUR_UTCONNECT_SUCCESS = "GET_FITUR_UTCONNECT_SUCCESS";

//PROMOTION
export const IMAGE_SLIDER_REQ = "IMAGE_SLIDER_REQ";
export const IMAGE_SLIDER_SUCCESS = "IMAGE_SLIDER_SUCCESS";
export const IMAGE_SLIDER_FAILED = "IMAGE_SLIDER_FAILED";
export const PROMOTION_LIST_REQ = "PROMOTION_LIST_REQ";
export const PROMOTION_LIST_SUCCESS = "PROMOTION_LIST_SUCCESS";
export const PROMOTION_LIST_FAILED = "PROMOTION_LIST_FAILED";
export const PROMOTION_DETAIL_REQ = "PROMOTION_DETAIL_REQ";
export const PROMOTION_DETAIL_SUCCESS = "PROMOTION_DETAIL_SUCCESS";
export const PROMOTION_DETAIL_FAILED = "PROMOTION_DETAIL_FAILED";
export const PROMOTION_HEADER_LIST_REQ = "PROMOTION_HEADER_LIST_REQ";
export const PROMOTION_HEADER_LIST_SUCCESS = "PROMOTION_HEADER_LIST_SUCCESS";
export const PROMOTION_HEADER_LIST_FAILED = "PROMOTION_HEADER_LIST_FAILED";

// BRAND
export const BRAND_REQ = "BRAND_REQ";
export const BRAND_SUCCESS = "BRAND_SUCCESS";
export const BRAND_FAILED = "BRAND_FAILED";

// List product
export const LIST_PRODUCT_REQ = "LIST_PRODUCT_REQ";
export const LIST_PRODUCT_SUCCESS = "LIST_PRODUCT_SUCCESS";
export const LIST_PRODUCT_FAILED = "LIST_PRODUCT_FAILED";

// Branch / Cabang
export const BRANCH_LIST_REQ = "BRANCH_LIST_REQ";
export const BRANCH_LIST_FAILED = "BRANCH_LIST_FAILED";
export const BRANCH_LIST_SUCCESS = "BRANCH_LIST_SUCCESS";

// Cek Price
export const CHECKPRICE_REQ = "CHECKPRICE_REQ";
export const CHECKPRICE_SUCCESS = "CHECKPRICE_SUCCESS";
export const CHECKPRICE_FAILED = "CHECKPRICE_FAILED";

// block login
export const RELEASE_BLOCK_LOGIN = "RELEASE_BLOCK_LOGIN";
export const SET_BLOCK_LOGIN = "SET_BLOCK_LOGIN";
export const COUNT_FAILED_LOGIN = "COUNT_FAILED_LOGIN";
export const INITIAL_FAILED_LOGIN_STATUS = "INITIAL_FAILED_LOGIN_STATUS";

// Upload File CSV
export const UPLOAD_CSV_REQ = "UPLOAD_CSV_REQ";
export const UPLOAD_CSV_SUCCESS = "UPLOAD_CSV_SUCCESS";
export const UPLOAD_CSV_FAILED = "UPLOAD_CSV_FAILED";
export const UPLOAD_FILE_REQ = "UPLOAD_FILE_REQ";
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_FAILED = "UPLOAD_FILE_FAILED";
export const DOWNLOAD_CSV_REQ = "DOWNLOAD_CSV_REQ";
export const DOWNLOAD_CSV_SUCCESS = "DOWNLOAD_CSV_SUCCESS";
export const DOWNLOAD_CSV_FAILED = "DOWNLOAD_CSV_FAILED";

// Detail Product
export const DETAIL_PRODUCT_REQ = "DETAIL_PRODUCT_REQ";
export const DETAIL_PRODUCT_SUCCESS = "DETAIL_PRODUCT_SUCCESS";
export const DETAIL_PRODUCT_FAILED = "DETAIL_PRODUCT_FAILED";
export const DETAIL_PRODUCT_REVIEW_REQ = "DETAIL_PRODUCT_REVIEW_REQ";
export const DETAIL_PRODUCT_REVIEW_SUCCESS = "DETAIL_PRODUCT_REVIEW_SUCCESS";
export const DETAIL_PRODUCT_REVIEW_FAILED = "DETAIL_PRODUCT_REVIEW_FAILED";

// Wishlist
export const WISHLIST_POST_REQ = "WISHLIST_POST_REQ";
export const WISHLIST_POST_SUCCESS = "WISHLIST_POST_SUCCESS";
export const WISHLIST_POST_FAILED = "WISHLIST_POST_FAILED";
export const WISHLIST_DEL_REQ = "WISHLIST_DEL_REQ";
export const WISHLIST_DEL_SUCCESS = "WISHLIST_DEL_SUCCESS";
export const WISHLIST_DEL_FAILED = "WISHLIST_DEL_FAILED";

// LISTNEWS
export const LIST_NEWS_REQ = "LIST_NEWS_REQ";
export const LIST_NEWS_SUCCESS = "LIST_NEWS_SUCCESS";
export const LIST_NEWS_FAILED = "LIST_NEWS_FAILED";

// GET WISHLIST
export const WISHLIST_GET_REQ = "WISHLIST_GET_REQ";
export const WISHLIST_GET_SUCCESS = "WISHLIST_GET_SUCCESS";
export const WISHLIST_GET_FAILED ="WISHLIST_GET_FAILED";

// CART
export const ADD_CART_REQ = "ADD_CART_REQ";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_FAILED = "ADD_CART_FAILED";
export const SEARCH_BY_USERID_REQ = "SEARCH_BY_USERID_REQ";
export const SEARCH_BY_USERID_SUCCESS = "SEARCH_BY_USERID_SUCCESS";
export const SEARCH_BY_USERID_FAILED = "SEARCH_BY_USERID_FAILED";
export const CART_LIST_REQ = "CART_LIST_REQ";
export const CART_LIST_SUCCESS = "CART_LIST_SUCCESS";
export const CART_LIST_FAILED = "CART_LIST_FAILED";
export const CART_LIST_BY_CARTID_REQ = "CART_LIST_BY_CARTID_REQ";
export const CART_LIST_BY_CARTID_SUCCESS = "CART_LIST_BY_CARTID_SUCCESS";
export const CART_LIST_BY_CARTID_FAILED = "CART_LIST_BY_CARTID_FAILED";

export const DELETE_CART_BY_CARTID_REQ = "DELETE_CART_BY_CARTID_REQ";
export const DELETE_CART_BY_CARTID_SUCCESS = "DELETE_CART_BY_CARTID_SUCCESS";
export const DELETE_CART_BY_CARTID_FAILED = "DELETE_CART_BY_CARTID_FAILED";
export const DELETE_ALL_CART_REQ = "DELETE_ALL_CART_REQ";
export const DELETE_ALL_CART_SUCCESS = "DELETE_ALL_CART_SUCCESS";
export const DELETE_ALL_CART_FAILED = "DELETE_ALL_CART_FAILED";

export const CART_LIST_BY_CARTID_PUT_REQ = "CART_LIST_BY_CARTID_PUT_REQ";
export const CART_LIST_BY_CARTID_PUT_SUCCESS = "CART_LIST_BY_CARTID_PUT_SUCCESS";
export const CART_LIST_BY_CARTID_PUT_FAILED = "CART_LIST_BY_CARTID_PUT_FAILED";

// SYARAT DAN KETENTUAN
export const TERM_CONDITION_REQ = "TERM_CONDITION_REQ";
export const TERM_CONDITION_SUCCESS = "TERM_CONDITION_SUCCESS";
export const TERM_CONDITION_FAILED = "TERM_CONDITION_FAILED";